services:
  db:
    image: postgres:latest
    container_name: 'postgresql-demo'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nagibator
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    volumes:
      - ./new_seed.dump:/dump/seed.dump
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
